title = "Angela Ridder's Safehouse"
baseurl = "/"
languageCode = "en-gb"
theme = "terminal"
pagination.pagerSize = 15

# Required for Chroma and the custom syntax highlighting.
[markup.highlight]
  noClasses = false

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  contentTypeName = "posts"
  showMenuItems = 2
  showLanguageSelector = false
  fullWidthTheme = false
  centerTheme = false
  autoCover = true
  showLastUpdated = true
  updatedDatePrefix = "Updated"
  # readingTime = false
  # Toc = false
  # TocTitle = "Table of Contents"
  # dateFormat = "2006-01-02"
  # dateFormat = "2006-01-02 3:04:06 PM MST"

[params.twitter]
  creator = "VoltealCodeGoat"
  site = "https://blog.angelaridder.com/"

[languages]
  [languages.en]
    languageName = "English"
    title = "Angela's Safehouse"

    [languages.en.params]
      subtitle = "An author's safehouse in a cyberpunk dystopia."
      owner = "Angela Ridder"
      keywords = ""
      copyright = "All copyrighted by Angela Ridder."
      menuMore = "Show more"
      readMore = "Read more"
      readOtherPosts = "Read other posts"
      newerPosts = "Newer posts"
      olderPosts = "Older posts"
      missingContentMessage = "Page not found..."
      missingBackButtonLabel = "Back to home page"
      minuteReadingTime = "min read"
      words = "words"

      [languages.en.params.logo]
        logoText = "Safehouse"
        logoHomeLink = "/"

      [languages.en.menu]
        [[languages.en.menu.main]]
          identifier = "about"
          name = "About"
          url = "/about"
